server:
  port: 8024

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: user-consumer
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:yang}
    password: ${RABBIT_MQ_PASSWORD:yang}
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
  endpoint:
    hystrix:
      stream:
        enabled: true
logging:
  level:
    org.springframework.web: debug
  path: logs/
  file:
    max-size: 1GB