server:
  port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: hystrix-turbine
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:yang}
    password: ${RABBIT_MQ_PASSWORD:yang}

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
turbine:
  app-config: PROVIDE-SERVER,USER-CONSUMER
  cluster-name-expression: new String("default")
  combine-host-port: true
  instanceUrlSuffix: /hystrix.stream
  aggregator:
    cluster-config: default
security:
  basic:
    enabled: false
